"""AI Business Summary — turn verified metrics into a short readable narrative.

Design stance: Python/SQL is the source of truth. The LLM receives ONLY the
verified metrics in outputs/metrics.json and is instructed never to invent,
recompute or modify a number. If no API key is present (or the call fails), a
deterministic template produces the same style of summary so the pipeline always
runs. This is presented as an experiment in using an LLM to *communicate*
verified results, not as an analytical engine.

Output: outputs/ai_summary.md
Run:  python src/ai_insights.py
"""
from __future__ import annotations

import json
import os
from pathlib import Path

from dotenv import load_dotenv

from config import OUTPUTS

PROMPT_RULES = """You are a careful business analyst writing a short summary for a
customer & campaign analytics report. You are given a JSON object of ALREADY
CALCULATED metrics.

Strict rules:
- Use ONLY the numbers provided in the JSON. Do NOT invent or estimate any number.
- Do NOT calculate new metrics or ratios that are not already in the JSON.
- Do NOT modify, round differently, or restate the provided values incorrectly.
- If something is not in the data, say the information is not available.
- Do not make unsupported claims about causes.
- Keep it concise: 4-6 short sentences or a few bullet points.
- Currency is INR. Write for a business reader.

Here is the verified metrics JSON:
"""


def _load_metrics() -> dict:
    with open(OUTPUTS / "metrics.json", "r", encoding="utf-8") as fh:
        return json.load(fh)


def _fmt_inr(x) -> str:
    try:
        return f"Rs {float(x):,.0f}"
    except (TypeError, ValueError):
        return "N/A"


def _pct(x) -> str:
    return "N/A" if x is None else f"{float(x) * 100:.1f}%"


def template_summary(m: dict) -> str:
    """Deterministic fallback — same information, no LLM required."""
    lines = ["# FinSight — AI Business Summary (template fallback)", ""]
    lines.append(
        f"Across the period ending {m.get('as_of', 'N/A')}, FinSight recorded "
        f"{_fmt_inr(m['total_revenue'])} in total revenue from "
        f"{m['total_transactions']:,} transactions by {m['active_customers']:,} "
        f"active customers, an average of {_fmt_inr(m['avg_transaction_value'])} per transaction."
    )
    if m.get("latest_month_revenue_growth_pct") is not None:
        lines.append(
            f"Revenue changed by {m['latest_month_revenue_growth_pct']:.2f}% in the "
            f"most recent month versus the previous month."
        )
    lines.append(
        f"The overall campaign redemption rate among engaged customers was "
        f"{_pct(m['campaign_redemption_rate'])}."
    )
    tc = m.get("top_campaign")
    if tc:
        lines.append(
            f"The top campaign by revenue was {tc['campaign_name']} ({tc['campaign_id']}) "
            f"with {_fmt_inr(tc['revenue'])} in campaign revenue and a "
            f"{_pct(tc['redemption_rate'])} redemption rate."
        )
    lc = m.get("lowest_redemption_campaign")
    if lc:
        lines.append(
            f"The weakest campaign on redemption was {lc['campaign_name']} "
            f"({lc['campaign_id']}) at {_pct(lc['redemption_rate'])}, which may warrant review."
        )
    ts = m.get("top_customer_segment")
    if ts:
        lines.append(
            f"The {ts['segment']} segment contributed the most revenue "
            f"({_fmt_inr(ts['revenue'])}). The repeat-customer rate was "
            f"{m['repeat_customer_rate_pct']}%."
        )
    lines.append(
        f"The pipeline flagged {m['anomalies_flagged']} anomalies for review. "
        f"The strongest revenue category was {m['top_category']}."
    )
    lines.append("")
    lines.append("_Generated without an LLM (no GEMINI_API_KEY set). All figures "
                 "are pre-computed by Python/SQL from synthetic data._")
    return "\n".join(lines)


def gemini_summary(m: dict, api_key: str, model_name: str) -> str:
    import google.generativeai as genai
    genai.configure(api_key=api_key)
    model = genai.GenerativeModel(model_name)
    prompt = PROMPT_RULES + json.dumps(m, indent=2)
    resp = model.generate_content(prompt)
    text = (resp.text or "").strip()
    if not text:
        raise RuntimeError("Empty response from Gemini")
    header = "# FinSight — AI Business Summary (Gemini)\n\n"
    footer = ("\n\n_Generated by Gemini from pre-computed metrics only. The model "
              "was instructed to use the supplied numbers and not to invent any._")
    return header + text + footer


def main() -> None:
    load_dotenv()
    m = _load_metrics()
    api_key = os.getenv("GEMINI_API_KEY", "").strip()
    model_name = os.getenv("GEMINI_MODEL", "gemini-1.5-flash").strip() or "gemini-1.5-flash"

    used = "template"
    if api_key:
        try:
            summary = gemini_summary(m, api_key, model_name)
            used = "gemini"
        except Exception as exc:  # any SDK/network/quota error -> graceful fallback
            print(f"[warn] Gemini call failed ({exc}); using template fallback.")
            summary = template_summary(m)
    else:
        print("[info] GEMINI_API_KEY not set; using template fallback.")
        summary = template_summary(m)

    OUTPUTS.mkdir(exist_ok=True)
    Path(OUTPUTS / "ai_summary.md").write_text(summary, encoding="utf-8")
    print(f"AI summary written to outputs/ai_summary.md (source: {used})\n")
    print(summary)


if __name__ == "__main__":
    main()
